### PR TITLE
fix issues with dll dependencies

### PR DESCRIPTION
**Pull request by marcelotduarte**
fix a regression introduced in #492
fix multiple get dependencies when the filename has different case

fix issues #504, #173 and maybe the related issues: #372, #328, #457, #455

### CODE REVIEW

**Comment by marcelotduarte** [comment]
This fix issues #504, #173 and maybe the related issues: #372, #328, #457, #455

**Comment by rerpha** [comment]
Are you planning on pushing a new release to pypy for this? I would like one as previously cx_freeze did not work for me on windows at all and it now does. Perhaps even just a minor/patch version? thanks. @anthony-tuininga

**Comment by marcelotduarte** [comment]
https://github.com/rerpha
Anthony has little spare time. He intended to release a version the week after commit. Let's hope he gets this week.

**Comment by rpodgorny** [comment]
it took me hours of trial and error and googling to finally land here. please make a stable release so others don't have to go through the same agony... ...thanks! ;-)

**Pull request merged**
