### PR TITLE
bdist_mac: Copy build_exe to Resources and move executables to MacOS

### PR DESCRIPTION
**Pull request by marcelotduarte**

### CODE REVIEW

**Comment by marcelotduarte** [comment]
@TechnicalPirate

**Comment by TechnicalPirate** [comment]
Hey trying to look at this today but `https://marcelotduarte.github.io/packages/cx-freeze/` seems to be down - will try again later! :)

**Comment by marcelotduarte** [comment]
@TechnicalPirate Please try again.

**Comment by TechnicalPirate** [comment]
Works! - Great improvement - ship it! :)

**Pull request merged**
