### PR TITLE
Added an option to put all dependences in one place.  Addresses issues #366.

### PR DESCRIPTION
**Pull request by cainesi**
Added a new parameter "small_app" to the Freezer object that, if true: 1) causes all dependencies to be copied into the top directory of the application (rather than the directory of the file that they are dependency of), and 2) causes ConsoleSmallApp.py to be used as the init script in place of Console.py.  ConsoleSmallApp.py is the same as Console.py, except that it causes the application's directory to be added to the PATH environment variable.  Addresses issue in #366.

### CODE REVIEW

**Comment by rockferd** [comment]
Are there any plans to release this change?

**Comment by cainesi** [comment]
> Are there any plans to release this change?

I am guessing not--the change is a bit ugly I think.  But you can just download the branch if you want to use it...

**Comment by marcelotduarte** [comment]
@anthony-tuininga and @cainesi 
The question about lot of files, I've been working on this, and have a few more things to do, especially for Windows, but I think we might have something minimal like what I did on PR #518.
We can close this PR?

**Comment by anthony-tuininga** [comment]
Yes, I think we can close this for now. @cainesi can update it or create a new one if he disagrees!

**Comment by cainesi** [comment]
> Yes, I think we can close this for now. @cainesi can update it or create a new one if he disagrees!

Whatever you think is best.  I will be interested in seeing a real solution when available, so I can stop using my kludgy patch.  Thanks for your work on this!

**Pull request closed without merging**
