### PR TITLE
Added a sample to illustrate problem with importlib.util.find_spec

### PR DESCRIPTION
**Pull request by cainesi**

### CODE REVIEW

**Comment by klensy** [comment]
https://docs.python.org/3.8/library/importlib.html#importlib.util.find_spec
>if name is for a submodule (contains a dot), the parent module is automatically imported.

Maybe that?

**Comment by cainesi** [comment]
> https://docs.python.org/3.8/library/importlib.html#importlib.util.find_spec
> 
> >if name is for a submodule (contains a dot), the parent module is automatically imported.
> 
> 
> 
> Maybe that?

Yes, indeed, that is exactly the problem. I've been thinking about how to fix it.

**Comment by marcelotduarte** [comment]
I already have a fix. In fact, I rewrote FindModule/LoadModule to use importlib.machinery and remove the deprecated 'imp', and with that solves this and other issues.

**Comment by cainesi** [comment]
> I already have a fix. In fact, I rewrote FindModule/LoadModule to use importlib.machinery and remove the deprecated 'imp', and with that solves this and other issues.

Great! It looks like master is still using imp, so those changes are not merged in yet?

**Comment by marcelotduarte** [comment]
I am finalizing some tests and I will put in a PR for tests for you.

**Pull request merged**
