### PR TITLE
Fixed cx_Freeze making faulty builds with Debian/Ubuntu distributed Python. (Issue #131)

### PR DESCRIPTION
**Pull request by peacegiverman**

### CODE REVIEW

**Comment by anthony-tuininga** [comment]
Thanks for providing this. It gave me an idea on how to improve this permanently: namely to calculate a path and then call Py_SetPath() with the result, rather than depend on the built-in functionality which is not consistent! I hope to check this in shortly and will then close this. I'd appreciate your comments on this.

**Comment by peacegiverman** [comment]
That sounds like a good idea. Making the path always consistent is a better solution.

**Comment by anthony-tuininga** [comment]
Py_SetPath() is only available in Python 3 so cx_Freeze 6 will contain this functionality (it will be Python 3 only). So I'm going to defer this for bit.

**Comment by anthony-tuininga** [comment]
Another solution has been implemented on both 5.x and master (6.x) branches of cx_Freeze. As mentioned earlier, thanks for the suggestions!

**Pull request closed without merging**
