### PR TITLE
Transform filename to msilib.Binary for binary data

### PR DESCRIPTION
**Pull request by Cimbali**
Only do this for columns marked binary, see #1019.

### CODE REVIEW

**Comment by marcelotduarte** [comment]
Can you add the use of this new option in the 'icon' sample to facilitate testing?

**Comment by Cimbali** [comment]
I’ve made a new sample of a realistic case where someone could want to use this (i.e. an icon different from the installer icon and from the executable icon), which also showcases how to add a row in another table.

**Comment by marcelotduarte** [comment]
runing bdist_msi I get:
```
creating dist
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    setup(
  File "c:\testes\cx_freeze\cx_Freeze\dist.py", line 397, in setup
    distutils.core.setup(**attrs)
  File "C:\Python38-64\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python38-64\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python38-64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\testes\cx_freeze\cx_Freeze\windist.py", line 847, in run
    self.add_config(fullname)
  File "c:\testes\cx_freeze\cx_Freeze\windist.py", line 139, in add_config
    data = [
  File "c:\testes\cx_freeze\cx_Freeze\windist.py", line 140, in <listcomp>
    row[:col] + [msilib.Binary(row[col])] + row[col + 1:]
TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by Cimbali** [comment]
Ah my bad. The ideal would be `(*row[:col], msilib.Binary(row[col]), *row[col + 1:])` but that’s Python 3.5+ I don’t know i that’s OK ?

**Comment by marcelotduarte** [comment]
cx-freeze supports python 3.6 to 3.9 (so f-strings, type annotation, etc)

**Comment by Cimbali** [comment]
Alright so we’re good then. The 9724621 commit should fix this.

**Comment by marcelotduarte** [comment]
I tested it but I don't see the icon. Using the icon sample, I see the executable with the icon, but using your sample msi_binary_data the icon doesn't show up.
image

**Comment by Cimbali** [comment]
It’s another icon that this example is setting.

**Comment by marcelotduarte** [comment]
How I can check it?

**Comment by Cimbali** [comment]
You can achieve the same as the other sample with the following options:

```
bdist_msi_options = {
    "data": {
        "Property": [
            ('ARPPRODUCTICON', 'IconId'),
        ],
        "Icon": [
            ('IconId', 'icon.ico'),
        ],
    },
}
```

**Comment by marcelotduarte** [comment]
With 7zip I see the reference in msi
image

**Comment by marcelotduarte** [comment]
Thanks!

**Pull request merged**
