### PR TITLE
support python 3.5.2 and up

### PR DESCRIPTION
**Pull request by marcelotduarte**
use dis._unpack_opargs

### CODE REVIEW

**Comment by anthony-tuininga** [comment]
Can you provide a bit more detail on why this patch is needed?

**Comment by marcelotduarte** [comment]
Only to organize, to not test the python version in each call.
But for me, I think that the preferable is to remove and support py 3.5.2 and up because this code is valid only for py35. For py36 and up the unpack is different.

**Comment by anthony-tuininga** [comment]
I agree. Supporting Python 3.5.2 and up is preferable to adding code for 3.5.0 and 3.5.1. So does that mean you'll close this and create a new PR that simply checks for 3.5.2 in setup.py?

**Comment by marcelotduarte** [comment]
I'll update this PR.

**Comment by marcelotduarte** [comment]
updated.

**Comment by anthony-tuininga** [comment]
Yep. Thanks!

**Pull request merged**
