### PR TITLE
bdist_mac: create symlink between folders specified by user under Resources

### PR DESCRIPTION
**Pull request by wanghaisheng**
https://github.com/marcelotduarte/cx_Freeze/discussions/2167 fix create symlink between folders under Resources to Contents/Macos when bdis_dmg

### CODE REVIEW

**Comment by wanghaisheng** [comment]
it works well
image

**Comment by marcelotduarte** [comment]
I fixed the checks, I'll test it later.

**Comment by wanghaisheng** [comment]
> I fixed the checks, I'll test it later.

this is my first pull request to another one`s repo

**Comment by marcelotduarte** [comment]
[Release 6.15.12](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.12) is out!

**Pull request merged**
