### PR TITLE
always use importlib_metadata

### PR DESCRIPTION
**Pull request by marcelotduarte**
this is a complement to PR #819

### CODE REVIEW

**Comment by klensy** [comment]
Btw, this is not the only place where `importlib_metadata` imported, so, it won't became inconsistent?

**Comment by marcelotduarte** [comment]
Where? In the docs? That is for readthedocs.

**Comment by klensy** [comment]
https://github.com/marcelotduarte/cx_Freeze/blob/31dbf4e8b749bbe640922aada1b12b3c7a174923/cx_Freeze/__init__.py#L40

**Comment by marcelotduarte** [comment]
PR #822 
Thanks!

**Pull request merged**
